<?xml version="1.0" encoding="utf-8"?><Database Name="FeriefravaerDB" Class="FerieFravaerDBClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\FeriefravaerDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FeriefravaerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Indberetningstype" Member="Indberetningstypes">
    <Type Name="Indberetningstype">
      <Column Name="Id" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Navn" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ArbejdsugeTimer" Member="ArbejdsugeTimers">
    <Type Name="ArbejdsugeTimer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WeekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mandag" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Tirsdag" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Onsdag" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Torsdag" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Fredag" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Loerdag" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Soendag" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ferie" Member="Feries">
    <Type Name="Ferie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MedarbejderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FoersteFeriedag" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SidsteFeriedag" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FerieLoen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Godkendt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Afvist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Indberettet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Fravaer" Member="Fravaers">
    <Type Name="Fravaer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MedarbejderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FoersteFravaersdag" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="SidsteFravaersdag" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Godkendt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Afvist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Indberettet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>