#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerieFravaerFileGenerator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FeriefravaerDB")]
	public partial class FerieFravaerDBClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFerie(Ferie instance);
    partial void UpdateFerie(Ferie instance);
    partial void DeleteFerie(Ferie instance);
    partial void InsertFravaer(Fravaer instance);
    partial void UpdateFravaer(Fravaer instance);
    partial void DeleteFravaer(Fravaer instance);
    #endregion
		
		public FerieFravaerDBClassesDataContext() : 
				base(global::FerieFravaerFileGenerator.Properties.Settings.Default.FeriefravaerDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public FerieFravaerDBClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FerieFravaerDBClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FerieFravaerDBClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FerieFravaerDBClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ferie> Feries
		{
			get
			{
				return this.GetTable<Ferie>();
			}
		}
		
		public System.Data.Linq.Table<Fravaer> Fravaers
		{
			get
			{
				return this.GetTable<Fravaer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ferie")]
	public partial class Ferie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _MedarbejderId;
		
		private System.DateTime _FoersteFeriedag;
		
		private System.DateTime _SidsteFeriedag;
		
		private bool _FerieLoen;
		
		private bool _Godkendt;
		
		private bool _Afvist;
		
		private bool _Indberettet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMedarbejderIdChanging(int value);
    partial void OnMedarbejderIdChanged();
    partial void OnFoersteFeriedagChanging(System.DateTime value);
    partial void OnFoersteFeriedagChanged();
    partial void OnSidsteFeriedagChanging(System.DateTime value);
    partial void OnSidsteFeriedagChanged();
    partial void OnFerieLoenChanging(bool value);
    partial void OnFerieLoenChanged();
    partial void OnGodkendtChanging(bool value);
    partial void OnGodkendtChanged();
    partial void OnAfvistChanging(bool value);
    partial void OnAfvistChanged();
    partial void OnIndberettetChanging(bool value);
    partial void OnIndberettetChanged();
    #endregion
		
		public Ferie()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedarbejderId", DbType="Int NOT NULL")]
		public int MedarbejderId
		{
			get
			{
				return this._MedarbejderId;
			}
			set
			{
				if ((this._MedarbejderId != value))
				{
					this.OnMedarbejderIdChanging(value);
					this.SendPropertyChanging();
					this._MedarbejderId = value;
					this.SendPropertyChanged("MedarbejderId");
					this.OnMedarbejderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoersteFeriedag", DbType="Date NOT NULL")]
		public System.DateTime FoersteFeriedag
		{
			get
			{
				return this._FoersteFeriedag;
			}
			set
			{
				if ((this._FoersteFeriedag != value))
				{
					this.OnFoersteFeriedagChanging(value);
					this.SendPropertyChanging();
					this._FoersteFeriedag = value;
					this.SendPropertyChanged("FoersteFeriedag");
					this.OnFoersteFeriedagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SidsteFeriedag", DbType="Date NOT NULL")]
		public System.DateTime SidsteFeriedag
		{
			get
			{
				return this._SidsteFeriedag;
			}
			set
			{
				if ((this._SidsteFeriedag != value))
				{
					this.OnSidsteFeriedagChanging(value);
					this.SendPropertyChanging();
					this._SidsteFeriedag = value;
					this.SendPropertyChanged("SidsteFeriedag");
					this.OnSidsteFeriedagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FerieLoen", DbType="Bit NOT NULL")]
		public bool FerieLoen
		{
			get
			{
				return this._FerieLoen;
			}
			set
			{
				if ((this._FerieLoen != value))
				{
					this.OnFerieLoenChanging(value);
					this.SendPropertyChanging();
					this._FerieLoen = value;
					this.SendPropertyChanged("FerieLoen");
					this.OnFerieLoenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Godkendt", DbType="Bit NOT NULL")]
		public bool Godkendt
		{
			get
			{
				return this._Godkendt;
			}
			set
			{
				if ((this._Godkendt != value))
				{
					this.OnGodkendtChanging(value);
					this.SendPropertyChanging();
					this._Godkendt = value;
					this.SendPropertyChanged("Godkendt");
					this.OnGodkendtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Afvist", DbType="Bit NOT NULL")]
		public bool Afvist
		{
			get
			{
				return this._Afvist;
			}
			set
			{
				if ((this._Afvist != value))
				{
					this.OnAfvistChanging(value);
					this.SendPropertyChanging();
					this._Afvist = value;
					this.SendPropertyChanged("Afvist");
					this.OnAfvistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indberettet", DbType="Bit NOT NULL")]
		public bool Indberettet
		{
			get
			{
				return this._Indberettet;
			}
			set
			{
				if ((this._Indberettet != value))
				{
					this.OnIndberettetChanging(value);
					this.SendPropertyChanging();
					this._Indberettet = value;
					this.SendPropertyChanged("Indberettet");
					this.OnIndberettetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fravaer")]
	public partial class Fravaer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _MedarbejderId;
		
		private System.Nullable<System.DateTime> _FoersteFravaersdag;
		
		private System.Nullable<System.DateTime> _SidsteFravaersdag;
		
		private bool _Godkendt;
		
		private bool _Afvist;
		
		private bool _Indberettet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMedarbejderIdChanging(int value);
    partial void OnMedarbejderIdChanged();
    partial void OnFoersteFravaersdagChanging(System.Nullable<System.DateTime> value);
    partial void OnFoersteFravaersdagChanged();
    partial void OnSidsteFravaersdagChanging(System.Nullable<System.DateTime> value);
    partial void OnSidsteFravaersdagChanged();
    partial void OnGodkendtChanging(bool value);
    partial void OnGodkendtChanged();
    partial void OnAfvistChanging(bool value);
    partial void OnAfvistChanged();
    partial void OnIndberettetChanging(bool value);
    partial void OnIndberettetChanged();
    #endregion
		
		public Fravaer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedarbejderId", DbType="Int NOT NULL")]
		public int MedarbejderId
		{
			get
			{
				return this._MedarbejderId;
			}
			set
			{
				if ((this._MedarbejderId != value))
				{
					this.OnMedarbejderIdChanging(value);
					this.SendPropertyChanging();
					this._MedarbejderId = value;
					this.SendPropertyChanged("MedarbejderId");
					this.OnMedarbejderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoersteFravaersdag", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FoersteFravaersdag
		{
			get
			{
				return this._FoersteFravaersdag;
			}
			set
			{
				if ((this._FoersteFravaersdag != value))
				{
					this.OnFoersteFravaersdagChanging(value);
					this.SendPropertyChanging();
					this._FoersteFravaersdag = value;
					this.SendPropertyChanged("FoersteFravaersdag");
					this.OnFoersteFravaersdagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SidsteFravaersdag", DbType="DateTime2")]
		public System.Nullable<System.DateTime> SidsteFravaersdag
		{
			get
			{
				return this._SidsteFravaersdag;
			}
			set
			{
				if ((this._SidsteFravaersdag != value))
				{
					this.OnSidsteFravaersdagChanging(value);
					this.SendPropertyChanging();
					this._SidsteFravaersdag = value;
					this.SendPropertyChanged("SidsteFravaersdag");
					this.OnSidsteFravaersdagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Godkendt", DbType="Bit NOT NULL")]
		public bool Godkendt
		{
			get
			{
				return this._Godkendt;
			}
			set
			{
				if ((this._Godkendt != value))
				{
					this.OnGodkendtChanging(value);
					this.SendPropertyChanging();
					this._Godkendt = value;
					this.SendPropertyChanged("Godkendt");
					this.OnGodkendtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Afvist", DbType="Bit NOT NULL")]
		public bool Afvist
		{
			get
			{
				return this._Afvist;
			}
			set
			{
				if ((this._Afvist != value))
				{
					this.OnAfvistChanging(value);
					this.SendPropertyChanging();
					this._Afvist = value;
					this.SendPropertyChanged("Afvist");
					this.OnAfvistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indberettet", DbType="Bit NOT NULL")]
		public bool Indberettet
		{
			get
			{
				return this._Indberettet;
			}
			set
			{
				if ((this._Indberettet != value))
				{
					this.OnIndberettetChanging(value);
					this.SendPropertyChanging();
					this._Indberettet = value;
					this.SendPropertyChanged("Indberettet");
					this.OnIndberettetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
